// ===== 新聞來源定義 =====
const SOURCES = {
  // 國內（靜態示範資料保留 ettoday/chinatimes/storm，但即時抓取已移除其失效 RSS）
  udn:          { name:'聯合新聞網',    short:'UDN',       region:'domestic',      color:'#d62828', bg:'#fff0f0', url:'https://udn.com/search/word/2/%E9%A3%9F%E5%AE%89' },
  ltn:          { name:'自由時報',      short:'自由',       region:'domestic',      color:'#006400', bg:'#f0fff0', url:'https://search.ltn.com.tw/list?keyword=%E9%A3%9F%E5%AE%89' },
  ettoday:      { name:'ETtoday',      short:'ET',         region:'domestic',      color:'#e07b00', bg:'#fff8f0', url:'https://www.ettoday.net/tag/%E9%A3%9F%E5%AE%89/' },
  chinatimes:   { name:'中時新聞網',    short:'中時',       region:'domestic',      color:'#1a4b8c', bg:'#f0f4ff', url:'https://www.chinatimes.com/search/%E9%A3%9F%E5%AE%89' },
  storm:        { name:'風傳媒',        short:'Storm',      region:'domestic',      color:'#2d6a4f', bg:'#f0fff8', url:'https://www.storm.mg/search?q=%E9%A3%9F%E5%AE%89' },
  heho:         { name:'Heho健康',      short:'Heho',       region:'domestic',      color:'#00897b', bg:'#e0f2f1', url:'https://heho.com.tw/archives/category/food' },
  tvbs_health:  { name:'健康2.0',       short:'健康2.0',    region:'domestic',      color:'#e64a19', bg:'#fbe9e7', url:'https://health.tvbs.com.tw/nutrition-foodsafety' },
  yahoo_tw:     { name:'奇摩新聞',      short:'奇摩',       region:'domestic',      color:'#5f01b5', bg:'#ede7f6', url:'https://tw.news.yahoo.com/health/' },
  // 國際
  bbc:          { name:'BBC News',     short:'BBC',        region:'international', color:'#bb1919', bg:'#fff0f0', url:'https://www.bbc.com/news/topics/cg41ylwvgnxt' },
  nyt:          { name:'紐約時報',      short:'NYT',        region:'international', color:'#000000', bg:'#f8f8f8', url:'https://www.nytimes.com/search?query=food+safety' },
  reuters:      { name:'路透社',        short:'Reuters',    region:'international', color:'#ff7f00', bg:'#fff8f0', url:'https://www.reuters.com/search/news?blob=food+safety' },
  cnn:          { name:'CNN',          short:'CNN',        region:'international', color:'#cc0001', bg:'#fff0f0', url:'https://edition.cnn.com/search?q=food+safety' },
  guardian:     { name:'衛報',          short:'Guardian',   region:'international', color:'#005689', bg:'#f0f6ff', url:'https://www.theguardian.com/environment/food' },
  yahoo_health: { name:'Yahoo Health', short:'Yahoo',      region:'international', color:'#6001d2', bg:'#f3e5ff', url:'https://news.yahoo.com/rss/health' },
  who:          { name:'WHO',          short:'WHO',        region:'international', color:'#1565c0', bg:'#e3f2fd', url:'https://www.who.int/news' },
  // Google
  gnews_tw:     { name:'Google新聞(台灣)', short:'G新聞TW', region:'domestic',      color:'#4285f4', bg:'#f0f4ff', url:'https://news.google.com/rss/search?q=%E9%A3%9F%E5%AE%89&hl=zh-TW&gl=TW&ceid=TW:zh-Hant' },
  gnews_en:     { name:'Google News',     short:'G News',  region:'international', color:'#34a853', bg:'#f0fff4', url:'https://news.google.com/rss/search?q=food+safety&hl=en-US&gl=US&ceid=US:en' },
  gnews_home:   { name:'Google新聞(頭條)', short:'G頭條',   region:'domestic',      color:'#5f6368', bg:'#f1f3f4', url:'https://news.google.com/home?hl=zh-TW&gl=TW&ceid=TW:zh-Hant' },
  gtrends:      { name:'Google Trends',   short:'Trends',  region:'domestic',      color:'#ea4335', bg:'#fff5f5', url:'https://trends.google.com/trending/rss?geo=TW' },
};

// ===== 新聞資料 =====
const NEWS_DATA = [
  // 聯合新聞網
  {
    id:1, cat:'domestic', source:'udn',
    title:'北市抽查手搖飲料含糖量　3成超標需限期改善',
    summary:'台北市衛生局針對全市500家手搖飲料店進行含糖量抽驗，結果顯示約3成業者糖量標示與實際不符，已要求限期改善並列入追蹤。',
    date:'2026-04-28', views:3421,
    url:'https://udn.com/search/word/2/%E9%A3%9F%E5%AE%89',
  },
  {
    id:2, cat:'policy', source:'udn',
    title:'食安法修正草案出爐　業者違規罰鍰上限提高三倍',
    summary:'行政院送審食品安全衛生管理法修正草案，針對重大違規業者罰鍰上限由新台幣6億元提高至18億元，並增訂吹哨者保護條款。',
    date:'2026-04-20', views:4562,
    url:'https://udn.com/search/word/2/%E9%A3%9F%E5%AE%89%E6%B3%95',
  },
  // 自由時報
  {
    id:3, cat:'domestic', source:'ltn',
    title:'食藥署公布食品添加物使用新規　防腐劑上限調降',
    summary:'食品藥物管理署修正食品添加物使用規範，苯甲酸等5種常見防腐劑允許上限調降10%，新規將於2026年7月1日正式施行。',
    date:'2026-04-25', views:2108,
    url:'https://search.ltn.com.tw/list?keyword=%E9%A3%9F%E5%93%81%E6%B7%BB%E5%8A%A0%E7%89%A9',
  },
  {
    id:4, cat:'domestic', source:'ltn',
    title:'雞蛋場登記制上路　掃QR Code可查農場履歷',
    summary:'農業部推行蛋雞場登記制度全面上路，消費者掃描包裝QR Code即可查詢雞蛋從農場到門市的完整履歷，提升食品溯源透明度。',
    date:'2026-04-18', views:2930,
    url:'https://search.ltn.com.tw/list?keyword=%E9%9B%9E%E8%9B%8B%E5%B1%A5%E6%AD%B7',
  },
  // ETtoday
  {
    id:5, cat:'domestic', source:'ettoday',
    title:'傳統市場生魚片抽查出爐　寄生蟲檢出率偏高',
    summary:'衛生單位針對傳統市場生食水產品進行抽查，共抽驗120件，其中8件檢出寄生蟲卵，已要求業者加強冷凍處理並暫停販售。',
    date:'2026-04-23', views:5120,
    url:'https://www.ettoday.net/tag/%E9%A3%9F%E5%AE%89/',
  },
  {
    id:6, cat:'domestic', source:'ettoday',
    title:'網紅推薦炸物店被稽查　廢油重複使用遭停業',
    summary:'某知名網紅多次推薦的炸物攤位遭衛生局突擊稽查，現場發現使用廢食用油、超標酸價，依法開罰並命令停業至完成改善。',
    date:'2026-04-16', views:8830,
    url:'https://www.ettoday.net/tag/%E9%A3%9F%E5%AE%89/',
  },
  // 中時新聞網
  {
    id:7, cat:'policy', source:'chinatimes',
    title:'立院三讀通過　基因改造食品強制標示範圍擴大',
    summary:'立法院三讀通過食品安全衛生管理法部分條文修正案，基因改造原料含量超過0.9%即須強制標示，並溯及現行販售產品。',
    date:'2026-04-21', views:3105,
    url:'https://www.chinatimes.com/search/%E9%A3%9F%E5%AE%89%E6%B3%95',
  },
  {
    id:8, cat:'domestic', source:'chinatimes',
    title:'中南部醬油工廠稽查　2家檢出致癌物超標',
    summary:'衛生福利部食藥署針對醬油製造業者進行專案稽查，共稽查36家，2家業者檢出黃麴毒素超標，已封存問題品批次並開罰。',
    date:'2026-04-12', views:2756,
    url:'https://www.chinatimes.com/search/%E9%A3%9F%E5%93%81%E7%A8%BD%E6%9F%A5',
  },
  // 風傳媒
  {
    id:9, cat:'policy', source:'storm',
    title:'深度分析：台灣食安稽查人力嚴重不足的結構困境',
    summary:'全台食品業者逾20萬家，但衛生稽查員僅約800人，平均每人需負責250家。本文深入剖析人力缺口如何讓食安漏洞難以填補。',
    date:'2026-04-26', views:4211,
    url:'https://www.storm.mg/search?q=%E9%A3%9F%E5%AE%89%E7%A8%BD%E6%9F%A5',
  },
  {
    id:10, cat:'policy', source:'storm',
    title:'從源頭到餐桌：台灣食安溯源系統的建置與挑戰',
    summary:'政府推動食品雲端履歷平台多年，但業者申報率仍不足六成。風傳媒專訪農委會官員與食安學者，拆解溯源系統的核心障礙。',
    date:'2026-04-10', views:3688,
    url:'https://www.storm.mg/search?q=%E9%A3%9F%E5%93%81%E6%BA%AF%E6%BA%90',
  },
  // BBC
  {
    id:11, cat:'international', source:'bbc',
    title:'BBC：歐盟禁止4種農藥　台灣跟進修訂輸入標準',
    summary:'歐盟宣布禁止4種農藥在食品中殘留，台灣衛福部已啟動修訂程序，預計年底前完成公告，影響蔬果進口規範。BBC報導此波禁令的全球連鎖反應。',
    date:'2026-04-22', views:1875,
    url:'https://www.bbc.com/news/topics/cg41ylwvgnxt',
  },
  {
    id:12, cat:'international', source:'bbc',
    title:'BBC：英國速食業者因食品標示不實遭重罰　掀監管風潮',
    summary:'英國食品標準局對多家速食連鎖業者祭出重罰，原因是過敏原標示不實導致消費者住院，此案已引發多國食安主管機關的關注。',
    date:'2026-04-14', views:2340,
    url:'https://www.bbc.com/news/topics/cg41ylwvgnxt',
  },
  // 紐約時報
  {
    id:13, cat:'international', source:'nyt',
    title:'NYT深度報導：美國加工食品含糖量監管長期失靈',
    summary:'紐約時報調查發現，美國FDA對加工食品含糖量的規範存在重大漏洞，製造商得以利用多種糖類分拆標示以規避總量揭露義務。',
    date:'2026-04-19', views:6102,
    url:'https://www.nytimes.com/search?query=food+safety+sugar',
  },
  {
    id:14, cat:'international', source:'nyt',
    title:'NYT：全球食品供應鏈脆弱性　氣候變遷加劇污染風險',
    summary:'隨著極端氣候頻率增加，穀物運輸與儲存條件惡化，黃麴毒素與農藥殘留問題在多個發展中國家顯著上升，引發全球食安警報。',
    date:'2026-04-07', views:4523,
    url:'https://www.nytimes.com/search?query=food+safety+climate',
  },
  // 路透社
  {
    id:15, cat:'international', source:'reuters',
    title:'路透社：WHO發布新版食品安全五大要點指引',
    summary:'世界衛生組織更新食品安全手冊，新增對網購生鮮食品的冷鏈要求指引，並特別強調家庭廚房的交叉污染預防為降低全球食因性疾病的關鍵。',
    date:'2026-04-24', views:3287,
    url:'https://www.reuters.com/search/news?blob=food+safety+WHO',
  },
  {
    id:16, cat:'international', source:'reuters',
    title:'路透社：東南亞爆發沙門氏菌集體感染　追查源頭至雞蛋農場',
    summary:'路透社報導，東南亞多國出現沙門氏菌集體感染事件，溯源調查指向同一跨國雞蛋供應商，已導致三國啟動緊急下架程序。',
    date:'2026-04-17', views:5012,
    url:'https://www.reuters.com/search/news?blob=salmonella+food+safety',
  },
  // CNN
  {
    id:17, cat:'international', source:'cnn',
    title:'CNN：美國即食沙拉遭李斯特菌污染　多州聯合下架',
    summary:'美國疾管署與FDA聯合調查後確認，某品牌即食沙拉產品遭李斯特菌污染，已波及12州，12人住院、1人死亡，製造商全面召回。',
    date:'2026-04-27', views:7890,
    url:'https://edition.cnn.com/search?q=food+recall+listeria',
  },
  {
    id:18, cat:'international', source:'cnn',
    title:'CNN：超加工食品與慢性病關聯性研究再度引發政策辯論',
    summary:'刊載於《柳葉刀》的最新研究顯示，超加工食品攝取量與代謝症候群風險呈顯著正相關，CNN採訪多位營養學家，探討政府是否應立法限制廣告。',
    date:'2026-04-13', views:6231,
    url:'https://edition.cnn.com/search?q=ultra-processed+food+health',
  },
  // 衛報
  {
    id:19, cat:'international', source:'guardian',
    title:'衛報：農藥使用量創20年新高　蜂群崩潰威脅食品安全',
    summary:'《衛報》調查報告指出，全球農藥使用量較2005年上升42%，新型菸鹼類農藥對蜂群的傷害導致授粉危機，間接威脅全球糧食供應穩定性。',
    date:'2026-04-25', views:4108,
    url:'https://www.theguardian.com/environment/food',
  },
  {
    id:20, cat:'international', source:'guardian',
    title:'衛報：塑膠微粒進入食物鏈　多國海鮮樣本驗出超標',
    summary:'衛報獨家報導，橫跨歐亞16國的聯合研究在市售貝類、魚類樣本中均檢出微塑膠顆粒，引發科學界對長期食用安全性的嚴重擔憂。',
    date:'2026-04-09', views:5643,
    url:'https://www.theguardian.com/environment/microplastics',
  },
];

// ===== 稽查報告資料 =====
const INSPECTION_DATA = [
  { date:'2026-04-28', name:'幸福小吃部', type:'restaurant', items:'衛生環境、食材溫度', result:'pass', action:'無' },
  { date:'2026-04-27', name:'新鮮生機股份有限公司', type:'factory', items:'農藥殘留、添加物', result:'warn', action:'限期改善' },
  { date:'2026-04-26', name:'台北東門市場', type:'market', items:'生熟食分離、溫控', result:'pass', action:'無' },
  { date:'2026-04-25', name:'大潤發中和店', type:'supermarket', items:'標示查核、效期管理', result:'warn', action:'限期改善' },
  { date:'2026-04-24', name:'美味廚坊餐廳', type:'restaurant', items:'廚房衛生、員工健康', result:'pass', action:'無' },
  { date:'2026-04-23', name:'金農食品股份有限公司', type:'factory', items:'防腐劑殘留、重金屬', result:'fail', action:'停業改善+罰鍰' },
  { date:'2026-04-22', name:'南門市場', type:'market', items:'生鮮食材保存溫度', result:'pass', action:'無' },
  { date:'2026-04-21', name:'全聯福利中心士林店', type:'supermarket', items:'效期標示、冷藏溫度', result:'pass', action:'無' },
];

// ===== 食安知識資料 =====
const TIPS_DATA = [
  {
    id:1, icon:'🌡️', cat:'冷鏈保存', catColor:'#ebf8ff', catTextColor:'#2b6cb0',
    title:'食物保存溫度全攻略',
    body:'冷藏室應維持0–7°C，冷凍室維持-18°C以下。熟食存放超過2小時需丟棄或加熱至中心溫度75°C以上，避免細菌繁殖。',
  },
  {
    id:2, icon:'🧼', cat:'個人衛生', catColor:'#f0fff4', catTextColor:'#276749',
    title:'正確洗手五步驟防食安風險',
    body:'處理食材前後務必以肥皂搓洗雙手20秒以上，包括指縫、大拇指及手腕。流動清水沖洗後以乾淨紙巾擦乾，可有效降低交叉污染。',
  },
  {
    id:3, icon:'🏷️', cat:'標示判讀', catColor:'#faf5ff', catTextColor:'#6b46c1',
    title:'看懂食品標示　效期不踩雷',
    body:'「有效日期」是品質保證期限；「賞味期限」前風味最佳但未必不可食；「製造日期」需自行計算。開封後效期縮短，應儘速食用。',
  },
  {
    id:4, icon:'🥦', cat:'農藥殘留', catColor:'#fffff0', catTextColor:'#744210',
    title:'蔬菜水洗去農藥正確方式',
    body:'流水沖洗比浸泡更有效：先沖洗整顆蔬菜表面，再去除外葉，切段後再次沖洗。高麗菜、花椰菜等葉菜類建議浸泡清水10分鐘再沖洗。',
  },
  {
    id:5, icon:'🐟', cat:'生食安全', catColor:'#fff5f5', catTextColor:'#c53030',
    title:'生食水產品　免疫力不佳者應避免',
    body:'生魚片等生食水產含有寄生蟲風險，兒童、孕婦、老人及免疫低下者應避免食用。選購時注意是否標示「供生食用」及低溫保存。',
  },
  {
    id:6, icon:'🫙', cat:'添加物', catColor:'#ebf8ff', catTextColor:'#2b6cb0',
    title:'常見食品添加物一覽與安全評估',
    body:'合法添加物如磷酸鹽、亞硝酸鹽在法定用量下安全無虞。消費者若有疑慮，可選購「無添加」或「有機認證」產品，並養成閱讀成分表的習慣。',
  },
];

// ===== 下架召回資料 =====
const RECALL_DATA = [
  {
    name:'XXX牌香腸（300g）', brand:'XX食品股份有限公司',
    reason:'亞硝酸鹽超標（實測值：200 mg/kg，限量70 mg/kg）',
    date:'2026-04-27', batch:'批號：2026-03-15', status:'open',
  },
  {
    name:'進口義大利奶酪（200g）', brand:'YY進口貿易商',
    reason:'檢出李斯特菌，可能導致食物中毒',
    date:'2026-04-24', batch:'效期：2026-06-30以前', status:'open',
  },
  {
    name:'花生奶油麵包（6入）', brand:'ZZ烘焙坊',
    reason:'成分標示未揭露花生過敏原，可能危害過敏族群',
    date:'2026-04-20', batch:'全批次', status:'open',
  },
  {
    name:'有機黑豆醬油（500ml）', brand:'WW有機農場',
    reason:'防腐劑苯甲酸超標（實測值：1.2 g/kg，限量1.0 g/kg）',
    date:'2026-04-15', batch:'批號：B2026041', status:'closed',
  },
  {
    name:'冷凍蝦仁（1kg）', brand:'AA水產股份有限公司',
    reason:'檢出氯霉素殘留，禁用於食用水產品',
    date:'2026-04-10', batch:'效期2026-12前全批', status:'closed',
  },
];

// ===== 跑馬燈 =====
const MARQUEE_ITEMS = [
  '【公告】4月份市場專項稽查結果公布，合格率96.4%，詳情請見稽查報告。',
  '【警示】XXX牌香腸亞硝酸鹽超標，請立即停止食用並退貨。',
  '【提醒】5月份將加強手搖飲料店衛生稽查，業者請確認標示合規。',
  '【活動】食安知識月：4月28日至5月31日參加線上測驗即可獲得電子證書。',
  '【法規】食品添加物新規7月1日施行，業者請儘速完成調整。',
];

// ===== 邊境查驗不符合資料（輸入食品，資料來源：衛福部食藥署 TFDA）=====
// 由 邊境不符合事項(2026年).xlsx 轉換；month 為月份(1–6)，date 為公告日期
const BORDER_CAT_COLORS = {
  '農藥殘留': '#e07b00', '重金屬': '#8e24aa', '溶出試驗': '#00838f', '甜味劑': '#c2185b',
  '防腐劑': '#5e35b1', '螢光增白劑': '#1565c0', '漂白劑': '#0277bd', '著色劑': '#d81b60',
  '動物用藥': '#6d4c41', '微生物': '#c62828', '戴奧辛': '#37474f', '衛生項目': '#455a64',
  '真菌毒素': '#ad1457', '保水劑': '#00695c', '食品添加物': '#7b1fa2', '防腐劑/抗氧化劑': '#5e35b1',
};
const BORDER_DATA = [
  { month:6, date:"2026-06-02", country:"印度", item:"阿薩姆茶", category:"農藥殘留", violation:"賽速安2.2 ppm", standard:"賽速安於茶類容許量為1.0 ppm" },
  { month:6, date:"2026-06-02", country:"菲律賓", item:"紙碗", category:"溶出試驗", violation:"以聚乙烯(PE)塗層之紙類製品，其於溶出試驗之檢測結果，高錳酸鉀消耗量(95℃，30分鐘)為16 ppm，以水(95℃，30分鐘)溶出之蒸發殘渣值為85 ppm，以4%醋酸(95℃，30分鐘)溶出之蒸發殘渣值為843 ppm", standard:"紙類-與食品直接接觸面之部分為以聚乙烯(PE)為合成原料之塑膠類者，其溶出試驗應符合該塑膠類之有關規定，高錳酸鉀消耗量(95℃，30分鐘)為10 ppm以下，以水(95℃，30分鐘)溶出之蒸發殘渣值為30 ppm以下，以4%醋酸(95℃，30分鐘)溶出之蒸發殘渣值為30 ppm以下" },
  { month:6, date:"2026-06-02", country:"德國", item:"鈣發泡錠(檸檬口味)", category:"甜味劑", violation:"甜味劑糖精2.28 g/kg、環己基(代)磺醯胺酸9.33 g/kg", standard:"液態膳食補充品甜味劑糖精用量以Saccharin計為0.08 g/L以下、環己基(代)磺醯胺酸用量以Cyclamate計為0.4 g/L以下，且混合使用甜味劑時，每一種甜味劑之使用量除以其用量標準所得之數值(即使用量/用量標準)總和不得大於1" },
  { month:6, date:"2026-06-02", country:"中國大陸", item:"桂花乾", category:"農藥殘留", violation:"農藥毆蟎多0.15 ppm、百克敏0.06 ppm、克凡派0.07 ppm、陶斯松0.07 ppm、三落松0.30 ppm", standard:"毆蟎多、陶斯松皆為不得檢出" },
  { month:6, date:"2026-06-02", country:"印尼", item:"木薯脆片", category:"甜味劑", violation:"甜味劑環己基（代）磺醯胺酸0.04 g/kg", standard:"產品非表列准用之食品範圍" },
  { month:6, date:"2026-06-02", country:"泰國", item:"蘆筍", category:"農藥殘留", violation:"克凡派0.11 ppm", standard:"克凡派於蘆筍容許量為0.05 ppm" },
  { month:6, date:"2026-06-02", country:"越南", item:"紫米", category:"農藥殘留", violation:"克美素0.05 ppm", standard:"克美素於米類為不得檢出" },
  { month:6, date:"2026-06-09", country:"孟加拉", item:"芝麻", category:"農藥殘留", violation:"二‧四地0.02 ppm", standard:"二‧四地於乾豆類為不得檢出" },
  { month:6, date:"2026-06-09", country:"日本", item:"日本絨螯蟹", category:"戴奧辛", violation:"戴奧辛8.0 pg WHO-TEQ/ g wet weight、戴奧辛與戴奧辛類多氯聯苯含量總和10.1 pg WHO-TEQ/ g wet weight", standard:"戴奧辛限值為3.5 pg WHO-TEQ/ g wet weight、戴奧辛與戴奧辛類多氯聯苯含量總和限值為6.5 pg WHO-TEQ/ g wet weight" },
  { month:6, date:"2026-06-09", country:"日本", item:"日本絨螯蟹", category:"戴奧辛", violation:"戴奧辛4.5 pg WHO-TEQ/ g wet weight", standard:"奧辛限值為 3.5 pg WHO-TEQ/ g wet weight" },
  { month:6, date:"2026-06-09", country:"中國大陸", item:"鮮南瓜", category:"農藥殘留", violation:"克美素2.25 ppm", standard:"克美素於瓜菜類為不得檢出，應低於檢測方法之定量極限0.01 ppm" },
  { month:6, date:"2026-06-09", country:"法國", item:"乾酪", category:"微生物", violation:"大腸桿菌43 MPN/g、23 MPN/g、23 MPN/g、23 MPN/g、43 MPN/g", standard:"大腸桿菌於乾酪類之檢驗結果判定，5個樣品中，允許有≦2個樣品之微生物檢驗值介於10 MPN/g(mL)和100 MPN/g(mL)之間，但不得有任何一個樣品之檢驗值＞100 MPN/g(mL)" },
  { month:6, date:"2026-06-09", country:"越南", item:"紫米", category:"農藥殘留", violation:"克美素0.05 ppm", standard:"克美素於米類為不得檢出" },
  { month:6, date:"2026-06-16", country:"中國大陸", item:"冷凍菠菜", category:"農藥殘留", violation:"滅芬諾0.03 ppm", standard:"滅芬諾以其他*0.01 ppm為法規容許值" },
  { month:6, date:"2026-06-16", country:"中國大陸", item:"冰鮮黃花魚", category:"動物用藥", violation:"恩氟喹啉羧酸0.01 ppm", standard:"恩氟喹啉羧酸於魚類各部位均為不得檢出" },
  { month:6, date:"2026-06-16", country:"緬甸", item:"紅茶粉", category:"著色劑", violation:"檢出食用黃色四號、食用黃色五號", standard:"產品非前述著色劑表列准用之食品範圍" },
  { month:6, date:"2026-06-16", country:"美國", item:"奧勒岡", category:"農藥殘留", violation:"環氧乙烷57.6 mg/kg", standard:"環氧乙烷為不得檢出，應低於檢測方法之定量極限0.1 mg/kg" },
  { month:6, date:"2026-06-16", country:"日本", item:"絨螯蟹", category:"戴奧辛", violation:"戴奧辛4.9 pg WHO-TEQ/ g wet weight", standard:"戴奧辛限值為3.5 pg WHO-TEQ/ g wet weight" },
  { month:6, date:"2026-06-16", country:"法國", item:"黑松露", category:"重金屬", violation:"鎘4 mg/kg", standard:"鎘於菇蕈類限量為2 mg/kg" },
  { month:6, date:"2026-06-16", country:"法國", item:"黑松露", category:"重金屬", violation:"鎘4 mg/kg", standard:"鎘於菇蕈類限量為2 mg/kg" },
  { month:6, date:"2026-06-16", country:"德國", item:"鐵+B群水果鐵飲", category:"防腐劑", violation:"防腐劑己二烯酸1.4 g/kg", standard:"Sorbic Acid 計為0.5 g/kg以下" },
  { month:6, date:"2026-06-16", country:"法國", item:"奶油起司", category:"微生物", violation:"檢出大腸桿菌240 MPN/g、＞1100 MPN/g、＞1100 MPN/g、240 MPN/g、＞1100 MPN/g", standard:"大腸桿菌於乾酪類之檢驗結果判定，5個樣品中，允許有≦2個樣品之微生物檢驗值介於10 MPN/g(mL)和100 MPN/g(mL)之間，但不得有任何一個樣品之檢驗值＞100 MPN/g(mL)" },
  { month:6, date:"2026-06-16", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"甜味劑糖精0.09 g/kg及環己基（代）磺醯胺酸0.97 g/kg", standard:"產品非表列准用之食品範圍" },
  { month:6, date:"2026-06-16", country:"中國大陸", item:"蒸籠紙", category:"溶出試驗", violation:"案內產品以4%醋酸(95℃，30分鐘)溶出試驗結果，蒸發殘渣值為75 ppm", standard:"紙類與食品直接接觸面之部分為塑膠類，應符合塑膠類之有關規定，非附表二所列材質者，其溶出試驗應符合「金屬合金類-與食品直接接觸面為合成樹脂塗漆者」之規定， 4%醋酸(95℃，30分鐘)蒸發殘渣值合格標準為30 ppm以下" },
  { month:6, date:"2026-06-16", country:"日本", item:"哈密瓜", category:"農藥殘留", violation:"依普同0.11 ppm", standard:"依普同以其他*0.01 ppm為法規容許值" },
  { month:6, date:"2026-06-16", country:"日本", item:"鮮蜜瓜", category:"農藥殘留", violation:"Nitenpyram 0.01 ppm", standard:"Nitenpyram於蜜瓜為不得檢出" },
  { month:6, date:"2026-06-23", country:"泰國", item:"橫簾蛤", category:"動物用藥", violation:"羥四環黴素 2.664 ppm、4-epimer-oxytetracycline 0.050 ppm", standard:"羥四環黴素、4-epimer-oxytetracycline於貝類皆為不得檢出" },
  { month:6, date:"2026-06-23", country:"中國大陸", item:"冰鮮黃花魚", category:"動物用藥", violation:"恩氟喹啉羧酸0.01 ppm", standard:"恩氟喹啉羧酸於魚類各部位均為不得檢出" },
  { month:6, date:"2026-06-23", country:"印尼", item:"黑胡椒粒", category:"農藥殘留", violation:"芬普尼0.004 ppm", standard:"芬普尼及其代謝物以其他*0.002 ppm為法規容許值" },
  { month:6, date:"2026-06-23", country:"越南", item:"冷凍白蝦仁", category:"動物用藥", violation:"脫氧羥四環黴素0.106 ppm", standard:"脫氧羥四環黴素蝦各部位均為不得檢出" },
  { month:6, date:"2026-06-23", country:"泰國", item:"南薑片", category:"重金屬", violation:"鉛4.5 mg/kg", standard:"鉛於香草植物及香辛植物類限量為0.3 mg/kg" },
  { month:6, date:"2026-06-23", country:"印尼", item:"果凍粉-巧克力風味", category:"防腐劑", violation:"苯甲酸0.02 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:6, date:"2026-06-23", country:"中國大陸", item:"桂花", category:"農藥殘留", violation:"益達胺0.19 ppm", standard:"益達胺以其他*0.05 ppm為法規容許值" },
  { month:6, date:"2026-06-23", country:"日本", item:"蜜柑", category:"農藥殘留", violation:"賽安勃0.02 ppm", standard:"賽安勃於蜜柑為不得檢出" },
  { month:6, date:"2026-06-23", country:"印尼", item:"香蕉乾餅", category:"甜味劑", violation:"環己基（代）磺醯胺酸0.17 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:6, date:"2026-06-23", country:"中國大陸", item:"燙金盒", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"以紙類與食品直接接觸面之部分為蠟或紙漿製品者為不得檢出" },
  { month:6, date:"2026-06-23", country:"中國大陸", item:"蛋糕盒", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"以紙類與食品直接接觸面之部分為蠟或紙漿製品者為不得檢出" },
  { month:6, date:"2026-06-30", country:"墨西哥", item:"白芝麻", category:"重金屬", violation:"鎘0.3 mg/kg", standard:"鎘於其他油籽限量為0.1 mg/kg" },
  { month:6, date:"2026-06-30", country:"越南", item:"冷凍白蝦仁", category:"動物用藥", violation:"脫氧羥四環黴素5.156 ppm和氟甲磺氯黴素0.032 ppm", standard:"脫氧羥四環黴素及氟甲磺氯黴素於蝦之肌肉均為不得檢出" },
  { month:6, date:"2026-06-30", country:"中國大陸", item:"冷凍馬蹄丁", category:"農藥殘留", violation:"克美素0.02 ppm", standard:"克美素於根莖菜類為不得檢出" },
  { month:6, date:"2026-06-30", country:"澳大利亞", item:"柑橘", category:"農藥殘留", violation:"芬普尼0.009 ppm", standard:"芬普尼及其代謝物以其他* 0.001 ppm為法規容許值" },
  { month:6, date:"2026-06-30", country:"中國大陸", item:"紙蓋", category:"溶出試驗", violation:"以聚丙烯(PP)塗層之紙類製品，其於溶出試驗之檢測結果，以水(95℃，30分鐘)溶出蒸發殘渣值為99 ppm，以4%醋酸(95℃，30分鐘)溶出蒸發殘渣值為3061 ppm，以20%乙醇(60℃，30分鐘)溶出蒸發殘渣值為76 ppm", standard:"紙類與食品直接接觸面之部分為聚丙烯(PP)者，其溶出試驗應符合該塑膠類之有關規定，水(95℃，30分鐘)、4%醋酸(95℃，30分鐘)、20%乙醇(60℃，30分鐘)蒸發殘渣值合格標準均為30 ppm以下，" },
  { month:6, date:"2026-06-30", country:"中國大陸", item:"一次性餐具", category:"溶出試驗", violation:"以4%醋酸(60℃，30分鐘)溶出試驗結果，蒸發殘渣值為32 ppm", standard:"以聚丙烯為合成原料之塑膠類，使用溫度未達100℃者，其以4%醋酸(60℃，30分鐘)溶出試驗蒸發殘渣標準為30 ppm以下" },
  { month:6, date:"2026-06-30", country:"越南", item:"榴槤", category:"農藥殘留", violation:"克美素0.03 ppm", standard:"克美素於大漿果類為不得檢出" },
  { month:6, date:"2026-06-30", country:"中國大陸", item:"桂花", category:"著色劑", violation:"蘇丹色素三號", standard:"蘇丹色素三號屬不得使用之物質" },
  { month:6, date:"2026-06-30", country:"中國大陸", item:"桂花", category:"農藥殘留", violation:"磷化氫0.044 ppm", standard:"磷化氫於草木本植物為不得檢出" },
  { month:6, date:"2026-06-30", country:"中國大陸", item:"馬芬杯", category:"溶出試驗", violation:"以4%醋酸(60℃，30分鐘)溶出試驗結果，蒸發殘渣值為92 ppm", standard:"以聚乙烯為合成原料之塑膠類，使用溫度未達100℃者，其以4%醋酸(60℃，30分鐘)溶出試驗蒸發殘渣標準為30 ppm以下</t></si></sst>" },
  { month:5, date:"2026-05-05", country:"日本", item:"嬰兒米果", category:"重金屬", violation:"鎘0.074 mg/kg", standard:"鎘於嬰幼兒穀物類輔助食品及嬰幼兒副食品中限量為0.040 mg/kg" },
  { month:5, date:"2026-05-05", country:"日本", item:"嬰兒米果", category:"重金屬", violation:"鎘0.045 mg/kg", standard:"鎘於嬰幼兒穀物類輔助食品及嬰幼兒副食品中限量為0.041 mg/kg" },
  { month:5, date:"2026-05-05", country:"泰國", item:"冷凍痲瘋柑葉", category:"農藥殘留", violation:"農藥菲克利0.02 ppm", standard:"菲克利以其他*0.01 ppm為法規容許值" },
  { month:5, date:"2026-05-05", country:"泰國", item:"冷凍痲瘋柑葉", category:"農藥殘留", violation:"農藥可尼丁0.03 ppm、畢達本0.04 ppm、賜派芬0.32 ppm、賽速安0.07 ppm、克凡派0.13 ppm、賽滅寧1.98 ppm", standard:"可尼丁、賜派芬、賽速安、克凡派、賽滅寧均以其他*0.01 ppm為法規容許值；畢達本於草木本植物為不得檢出，應低於檢測方法之定量極限0.01 ppm" },
  { month:5, date:"2026-05-05", country:"加拿大", item:"亞麻籽", category:"重金屬", violation:"鎘0.6 mg/kg", standard:"鎘於亞麻籽限量為0.5 mg/kg" },
  { month:5, date:"2026-05-05", country:"巴西", item:"胡椒粒", category:"農藥殘留", violation:"磷化氫0.05 ppm", standard:"磷化氫於香辛植物容許量為0.01 ppm" },
  { month:5, date:"2026-05-05", country:"美國", item:"冷凍草莓", category:"農藥殘留", violation:"農藥Fenhexamid 0.02 ppm", standard:"Fenhexamid於草莓為不得檢出，應低於檢測方法之定量極限0.01 ppm" },
  { month:5, date:"2026-05-05", country:"馬來西亞", item:"咖哩粉", category:"農藥殘留", violation:"農藥芬普尼0.004 ppm(芬普尼及其代謝物之加總為0.004 ppm)", standard:"芬普尼及其代謝物以其他* 0.002 ppm為法規容許值" },
  { month:5, date:"2026-05-05", country:"美國", item:"調味料", category:"農藥殘留", violation:"檢出殘留農藥芬普尼0.007 ppm，芬普尼代謝物0.004 ppm(芬普尼及其代謝物之加總為0.011 ppm)", standard:"芬普尼及其代謝物以其他* 0.002 ppm為法規容許值" },
  { month:5, date:"2026-05-05", country:"美國", item:"西洋參", category:"農藥殘留", violation:"檢出殘留農藥氟比來0.04 ppm、DDT 0.02 ppm、DDE 0.13 ppm", standard:"氟比來以其他* 0.01 ppm為法規容許值；DDT、DDE於西洋參皆為不得檢出" },
  { month:5, date:"2026-05-05", country:"日本", item:"藍莓", category:"農藥殘留", violation:"農藥氟尼胺0.07 ppm、諾伐隆0.12 ppm", standard:"氟尼胺以其他* 0.01 ppm為法規容許值；諾伐隆於藍莓為不得檢出" },
  { month:5, date:"2026-05-05", country:"中國大陸", item:"包裝盒(包裝盒)", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"紙類螢光增白劑不得檢出" },
  { month:5, date:"2026-05-05", country:"中國大陸", item:"紙盒(紙盒)", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"紙類螢光增白劑不得檢出" },
  { month:5, date:"2026-05-12", country:"美國", item:"黃豆", category:"農藥殘留", violation:"陶斯松0.03 ppm", standard:"陶斯松於乾豆類為不得檢出，應低於檢測方法之定量極限0.02 ppm" },
  { month:5, date:"2026-05-12", country:"肯亞", item:"咖啡豆", category:"農藥殘留", violation:"亞特松0.06 ppm", standard:"亞特松以其他*0.02 ppm為法規容許值" },
  { month:5, date:"2026-05-12", country:"韓國", item:"嬰兒米餅", category:"重金屬", violation:"鎘0.047 mg/kg", standard:"鎘於嬰幼兒穀物類輔助食品限量為0.040 mg/kg" },
  { month:5, date:"2026-05-12", country:"中國大陸", item:"橡膠手套", category:"溶出試驗", violation:"以水(95℃，30分鐘)溶出試驗結果，蒸發殘渣量為65 ppm，以20%乙醇(60℃，30分鐘)溶出試驗結果，蒸發殘渣量為66 ppm", standard:"溶出試驗以水(95℃，30分鐘)及20%乙醇(60℃，30分鐘)蒸發殘渣合格標準均為60 ppm以下" },
  { month:5, date:"2026-05-12", country:"衣索比亞", item:"綠豆", category:"農藥殘留", violation:"賽洛寧0.09 ppm", standard:"賽洛寧於乾豆類容許量為0.05 ppm" },
  { month:5, date:"2026-05-12", country:"智利", item:"冷凍海膽卵", category:"重金屬", violation:"鎘0.8 mg/kg", standard:"鎘於其他水產動物類限量為0.3 mg/kg" },
  { month:5, date:"2026-05-12", country:"日本", item:"塑膠茶托", category:"溶出試驗", violation:"以水(95℃，30分鐘)溶出試驗結果，高錳酸鉀消耗量為13 ppm", standard:"塑膠類溶出試驗以水(95℃，30分鐘)高錳酸鉀消耗量合格標準為10 ppm以下" },
  { month:5, date:"2026-05-12", country:"越南", item:"栗香地瓜", category:"農藥殘留", violation:"克美素0.05 ppm", standard:"克美素於根莖菜類為不得檢出，應低於檢測方法之定量極限0.01 ppm" },
  { month:5, date:"2026-05-12", country:"中國大陸", item:"砧板", category:"溶出試驗", violation:"以4%醋酸(95℃，30分鐘)溶出試驗結果，蒸發殘渣值為153 ppm", standard:"以聚丙烯為合成原料之塑膠類，其使用溫度達100℃者，溶出試驗以4%醋酸(95℃，30分鐘)的蒸發殘渣合格標準為30 ppm以下，" },
  { month:5, date:"2026-05-12", country:"日本", item:"藍莓", category:"農藥殘留", violation:"農藥氟尼胺0.08 ppm、諾伐隆0.1 ppm", standard:"氟尼胺以其他*0.01 ppm為法規容許值、諾伐隆於藍莓為不得檢出，應低於檢測方法之定量極限0.01 ppm" },
  { month:5, date:"2026-05-19", country:"中國大陸", item:"茉莉陳皮茯苓茶", category:"農藥殘留", violation:"農藥陶斯松0.09 ppm", standard:"陶斯松為不得檢出" },
  { month:5, date:"2026-05-19", country:"中國大陸", item:"茉莉陳皮茯苓茶", category:"漂白劑", violation:"二氧化硫0.065 g/kg", standard:"二氧化硫限量為0.030 g/kg" },
  { month:5, date:"2026-05-19", country:"中國大陸", item:"小茴香", category:"農藥殘留", violation:"農藥亞滅培0.18 ppm", standard:"亞滅培以其他*0.05 ppm為法規容許值" },
  { month:5, date:"2026-05-19", country:"中國大陸", item:"薄荷", category:"農藥殘留", violation:"第滅寧0.23 ppm、得克利3.87 ppm、賽速安0.38 ppm、三氟敏1.04 ppm", standard:"第滅寧於薄荷類容許量為0.2 ppm；得克利、賽速安、三氟敏皆以其他*0.05 ppm為法規容許值" },
  { month:5, date:"2026-05-19", country:"義大利", item:"新鮮茴香頭", category:"農藥殘留", violation:"待克利0.07 ppm、氟克殺0.02 ppm", standard:"待克利以其他*0.01 ppm為法規容許值、氟克殺於茴香為不得檢出" },
  { month:5, date:"2026-05-19", country:"中國大陸", item:"冷凍豌豆苗", category:"農藥殘留", violation:"農藥因得克0.02 ppm、巴克素0.09 ppm、克美素0.77 ppm", standard:"因得克、巴克素皆以其他*0.01 ppm為法規容許值，克美素為不得檢出" },
  { month:5, date:"2026-05-19", country:"日本", item:"鮮藍莓", category:"農藥殘留", violation:"派本克0.06 ppm", standard:"派本克於藍莓為不得檢出" },
  { month:5, date:"2026-05-19", country:"日本", item:"鮮哈密瓜", category:"農藥殘留", violation:"滅派林0.02 ppm", standard:"滅派林於哈密瓜為不得檢出" },
  { month:5, date:"2026-05-19", country:"越南", item:"黑糙米", category:"農藥殘留", violation:"歐索林酸0.04 ppm", standard:"歐索林酸於米類為不得檢出" },
  { month:5, date:"2026-05-26", country:"中國大陸", item:"手套", category:"溶出試驗", violation:"以水(60℃，30分鐘)溶出試驗結果，蒸發殘渣量為124 ppm，以20%乙醇(60℃，30分鐘)溶出試驗結果，蒸發殘渣量為270 ppm", standard:"橡膠-哺乳器具除外為原料之塑膠類者，其溶出試驗以水(60℃，30分鐘)及20%乙醇(60℃，30分鐘)蒸發殘渣合格標準均為60 ppm以下" },
  { month:5, date:"2026-05-26", country:"保加利亞", item:"新鮮黑松露", category:"重金屬", violation:"鎘3 mg/kg", standard:"鎘於菇蕈類限量為2 mg/kg" },
  { month:5, date:"2026-05-26", country:"保加利亞", item:"新鮮黑松露", category:"重金屬", violation:"鎘4 mg/kg", standard:"鎘於菇蕈類限量為2 mg/kg" },
  { month:5, date:"2026-05-26", country:"越南", item:"鮮榴槤", category:"農藥殘留", violation:"滅達樂0.02 ppm", standard:"滅達樂於榴槤為不得檢出" },
  { month:5, date:"2026-05-26", country:"中國大陸", item:"紅棗乾", category:"農藥殘留", violation:"陶斯松0.04 ppm", standard:"陶斯松梨果類為不得檢出" },
  { month:5, date:"2026-05-26", country:"印度", item:"小茴香子", category:"農藥殘留", violation:"佈飛松0.48 ppm", standard:"飛松以其他*0.05 ppm為法規容許值" },
  { month:5, date:"2026-05-26", country:"中國大陸", item:"紙罐", category:"溶出試驗", violation:"案內產品以20%乙醇(60℃，30分鐘)溶出試驗結果，蒸發殘渣為40 ppm、氯仿可溶物為477 ppm", standard:"溶出試驗以20%乙醇蒸發殘渣30 ppm以上者，其氯仿可溶物應為40 ppm以下" },
  { month:4, date:"2026-04-07", country:"南非", item:"夏威夷豆", category:"農藥殘留", violation:"協力精0.18 ppm", standard:"協力精為不得檢出" },
  { month:4, date:"2026-04-07", country:"印尼", item:"茉莉花茶", category:"甜味劑", violation:"甜味劑環己基（代）磺醯胺酸0.08 g/kg", standard:"產品非表列准用之食品範圍" },
  { month:4, date:"2026-04-07", country:"日本", item:"烏賊", category:"重金屬", violation:"鎘2 mg/kg", standard:"鎘於頭足類(不含內臟)限量為1 mg/kg" },
  { month:4, date:"2026-04-07", country:"中國大陸", item:"紙托(紙托)", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"紙類與食品直接接觸面之部分為蠟或紙漿製品者為不得檢出" },
  { month:4, date:"2026-04-07", country:"埃及", item:"牛膝草", category:"農藥殘留", violation:"賽洛寧0.14 ppm", standard:"賽洛寧以其他*0.03 ppm為法規容許值" },
  { month:4, date:"2026-04-14", country:"埃及", item:"薄荷茶", category:"農藥殘留", violation:"治滅蝨0.41 ppm", standard:"治滅蝨以其他*0.05 ppm為法規容許值" },
  { month:4, date:"2026-04-14", country:"中國大陸", item:"菊花", category:"農藥殘留", violation:"檢出殘留農藥亞滅培2.5 ppm、達滅芬9.3 ppm、氟尼胺0.09 ppm、因得克0.89 ppm、祿芬隆0.28 ppm、克凡派2.6 ppm、賽滅寧0.71 ppm 及派美尼0.42 ppm", standard:"亞滅培、克凡派於菊花容許量2.0 ppm；達滅芬容許量0.5 ppm；氟尼胺、祿芬隆皆以其他*0.05 ppm為法規容許值；因得克以其他*0.01 ppm為法規容許值；賽滅寧以其他*0.03 ppm為法規容許值；派美尼不得檢出，應低於檢測方法之定量極限0.05 ppm" },
  { month:4, date:"2026-04-14", country:"越南", item:"冷凍百香果汁", category:"農藥殘留", violation:"歐滅松0.01 ppm", standard:"歐滅松於百香果為不得檢出" },
  { month:4, date:"2026-04-14", country:"越南", item:"綠蘆筍", category:"農藥殘留", violation:"農藥可尼丁0.06 ppm及因滅汀0.013 ppm", standard:"可尼丁以其他*0.01 ppm為法規容許值；因滅汀於蘆筍為不得檢出，應低於檢測方法之定量極限0.007 ppm" },
  { month:4, date:"2026-04-14", country:"中國大陸", item:"乾竹蓀", category:"重金屬", violation:"鎘5 mg/kg", standard:"鎘於菇蕈類限量為2 mg/kg" },
  { month:4, date:"2026-04-14", country:"義大利", item:"乾酪", category:"微生物", violation:"檢出大腸桿菌93 MPN/g、23 MPN/g、23 MPN/g、23 MPN/g、93 MPN/g", standard:"大腸桿菌於乾酪類之檢驗結果判定，5個樣品中，允許有≦2個樣品之微生物檢驗值介於10 MPN/g(mL)和100 MPN/g(mL)之間，但不得有任何一個樣品之檢驗值＞100 MPN/g(mL)" },
  { month:4, date:"2026-04-14", country:"智利", item:"油桃", category:"農藥殘留", violation:"Fenhexamid 0.02 ppm", standard:"Fenhexamid為不得檢出" },
  { month:4, date:"2026-04-14", country:"印尼", item:"香蕉點心", category:"甜味劑", violation:"檢出甜味劑糖精0.11 g/kg及環己基(代)磺醯胺酸1.19 g/kg", standard:"產品非表列准用之食品範圍" },
  { month:4, date:"2026-04-14", country:"泰國", item:"蘆筍", category:"農藥殘留", violation:"普拔克0.02 ppm", standard:"普拔克以其他*0.01 ppm為法規容許值" },
  { month:4, date:"2026-04-14", country:"泰國", item:"蘆筍", category:"農藥殘留", violation:"普拔克0.02 ppm", standard:"普拔克以其他*0.01 ppm為法規容許值" },
  { month:4, date:"2026-04-21", country:"中國大陸", item:"茶具組", category:"溶出試驗", violation:"以4%醋酸常溫(暗處)24小時溶出試驗結果，檢出鉛39.7 ppm", standard:"玻璃、陶瓷器、施琺瑯之器具、容器-(b)深2.5cm 以上，且容量1.1L以上，其溶出試驗4%醋酸常溫(暗處)24小時鉛之合格標準為2.5 ppm以下" },
  { month:4, date:"2026-04-21", country:"越南", item:"冷凍地瓜", category:"農藥殘留", violation:"克美素0.05 ppm", standard:"克美素於地瓜不得檢出" },
  { month:4, date:"2026-04-21", country:"日本", item:"鮮藍莓", category:"農藥殘留", violation:"派本克0.13 ppm", standard:"派本克於藍莓為不得檢出" },
  { month:4, date:"2026-04-21", country:"日本", item:"鮮藍莓", category:"農藥殘留", violation:"派本克0.38 ppm", standard:"派本克於藍莓為不得檢出" },
  { month:4, date:"2026-04-21", country:"越南", item:"鮮榴槤", category:"農藥殘留", violation:"達特南0.01 ppm、撲滅寧0.03 ppm", standard:"達特南於榴槤為不得檢出/撲滅寧以其他* 0.01 ppm為法規容許值" },
  { month:4, date:"2026-04-21", country:"印尼", item:"炸雞用醬", category:"防腐劑", violation:"防腐劑丙酸0.6 g/kg", standard:"非表列准用之食品範圍" },
  { month:4, date:"2026-04-21", country:"法國", item:"肉桂粉", category:"重金屬", violation:"鉛1.0 mg/kg、鎘0.4 mg/kg", standard:"香草植物及香辛植物類鉛限量為0.3 mg/kg，鎘限量為0.2 mg/kg" },
  { month:4, date:"2026-04-21", country:"澳大利亞", item:"營養補充液", category:"防腐劑", violation:"己二烯酸0.9 g/kg", standard:"不含碳酸飲料之防腐劑用量以Sorbic Acid計為0.5 g/kg以下" },
  { month:4, date:"2026-04-21", country:"越南", item:"蘆筍", category:"農藥殘留", violation:"氟尼胺0.03 ppm", standard:"氟尼胺以其他*0.01 ppm為法規容許值" },
  { month:4, date:"2026-04-21", country:"越南", item:"綠蘆筍", category:"農藥殘留", violation:"滅芬諾0.02 ppm", standard:"滅芬諾以其他*0.01 ppm為法規容許值" },
  { month:4, date:"2026-04-21", country:"中國大陸", item:"淋膜袋", category:"溶出試驗", violation:"以4%醋酸(60℃，30分鐘)溶出試驗結果，蒸發殘渣值為33 ppm", standard:"以聚乙烯為合成原料之塑膠類，其溶出試驗4%醋酸(60℃，30分鐘)蒸發殘渣標準為30 ppm以下" },
  { month:4, date:"2026-04-21", country:"中國大陸", item:"蒸籠紙", category:"溶出試驗", violation:"以4%醋酸(95℃，30分鐘)溶出試驗結果，蒸發殘渣值為35 ppm", standard:"以紙類與食品直接接觸面之部分為塑膠類，溶出試驗以4%醋酸(95℃,30分鐘)蒸發殘渣值合格標準為30 ppm以下" },
  { month:4, date:"2026-04-21", country:"印尼", item:"天貝脆片", category:"甜味劑", violation:"甜味劑環己基（代）磺醯胺酸0.07 g/kg", standard:"產品非表列准用之食品範圍" },
  { month:4, date:"2026-04-28", country:"加拿大", item:"冷藏海膽卵", category:"重金屬", violation:"鎘0.5 mg/kg", standard:"鎘於其他水產動物類限量為0.3 mg/kg" },
  { month:4, date:"2026-04-28", country:"西班牙", item:"橄欖油", category:"食品添加物", violation:"銅葉綠素A 0.32 ppm", standard:"產品非表列准用之食品範圍" },
  { month:4, date:"2026-04-28", country:"中國大陸", item:"碳酸氫鈉", category:"食品添加物", violation:"氯化物（以Cl計）大於200 ppm", standard:"「食品添加物使用範圍及限量暨規格標準」，氯化物（以Cl計）為200 ppm以下，" },
  { month:4, date:"2026-04-28", country:"中國大陸", item:"辣椒乾", category:"著色劑", violation:"蘇丹色素三號", standard:"屬不得使用之物質" },
  { month:4, date:"2026-04-28", country:"中國大陸", item:"桂花", category:"農藥殘留", violation:"克凡派0.09 ppm、撲滅寧0.11 ppm", standard:"克凡派、撲滅寧均以其他* 0.05 ppm為法規容許值" },
  { month:4, date:"2026-04-28", country:"日本", item:"哈密瓜", category:"農藥殘留", violation:"滅派林0.03 ppm、Isofetamid 0.02 ppm", standard:"滅派林、Isofetamid於哈密瓜皆為不得檢出" },
  { month:3, date:"2026-03-03", country:"日本", item:"鮮金柑", category:"農藥殘留", violation:"賜滅芬2.4 ppm", standard:"賜滅芬於柑桔類容許量為1.0 ppm" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"黑芝麻", category:"重金屬", violation:"鎘0.2 mg/kg", standard:"鎘於其他油籽類限量為0.1 mg/kg" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"紙蓋", category:"溶出試驗", violation:"以正庚烷(25℃，1小時)溶出試驗結果，蒸發殘渣值102 ppm", standard:"聚乙烯(PE)、聚丙烯(PP)、聚對苯二甲酸乙二酯(PET)為原材料之塑膠類，溶出試驗以正庚烷(25℃，1小時)蒸發殘渣合格標準皆為30 ppm以下，" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"奶花雲豆", category:"農藥殘留", violation:"撲滅寧0.07 ppm", standard:"撲滅寧以其他*0.02 ppm為法規容許值" },
  { month:3, date:"2026-03-03", country:"泰國", item:"砂仁", category:"農藥殘留", violation:"2-Phenylphenol 0.12 ppm", standard:"2-Phenylphenol於香辛植物(果實)為不得檢出" },
  { month:3, date:"2026-03-03", country:"越南", item:"白米", category:"農藥殘留", violation:"氟派瑞0.04 ppm", standard:"氟派瑞於米類為不得檢出" },
  { month:3, date:"2026-03-03", country:"法國", item:"新鮮黑松露", category:"重金屬", violation:"鎘6 mg/kg", standard:"鎘於菇蕈類限量為2 mg/kg" },
  { month:3, date:"2026-03-03", country:"法國", item:"鱸魚", category:"重金屬", violation:"甲基汞0.6 mg/kg", standard:"甲基汞於其他魚類限量為0.5 mg/kg" },
  { month:3, date:"2026-03-03", country:"法國", item:"扇貝", category:"重金屬", violation:"鎘7 mg/kg", standard:"鎘於貝類(不含殼)限量為1 mg/kg。" },
  { month:3, date:"2026-03-03", country:"印尼", item:"冷凍小鯊魚", category:"重金屬", violation:"鎘0.08 mg/kg", standard:"鎘於其他魚類限量為0.05 mg/kg" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"烏梅", category:"農藥殘留", violation:"2-phenylphenol 0.09 ppm", standard:"2-phenylphenol於梅為不得檢出" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"桂花", category:"農藥殘留", violation:"磷化氫0.032 ppm", standard:"磷化氫於草木本植物為不得檢出" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"紅棗", category:"農藥殘留", violation:"佈飛松0.28 ppm、毆蟎多0.21 ppm", standard:"依佈飛松以其他*0.05 ppm為法規容許值；毆蟎多於紅棗為不得檢出" },
  { month:3, date:"2026-03-03", country:"德國", item:"水果風味飲", category:"防腐劑", violation:"己二烯酸0.9 g/kg", standard:"不含碳酸飲料類防腐劑己二烯酸用量以Sorbic Acid 計為0.5 g/kg以下" },
  { month:3, date:"2026-03-03", country:"智利", item:"鮮油桃", category:"農藥殘留", violation:"Fenhexamid 0.04 ppm", standard:"Fenhexamid為不得檢出" },
  { month:3, date:"2026-03-03", country:"中國大陸", item:"硅油纸盤", category:"溶出試驗", violation:"以4%醋酸(95℃,30分鐘)溶出試驗結果，蒸發殘渣值96 ppm", standard:"溶出試驗以4%醋酸(95℃,30分鐘)蒸發殘渣合格標準為30 ppm以下" },
  { month:3, date:"2026-03-03", country:"瑞士", item:"乾酪", category:"微生物", violation:"檢出大腸桿菌＞1100 MPN/g、210 MPN/g、23 MPN/g、43 MPN/g、23 MPN/g", standard:"大腸桿菌於乾酪類之檢驗結果判定，5個樣品中，允許有≦2個樣品之微生物檢驗值介於10 MPN/g(mL)和100 MPN/g(mL)之間，但不得有任何一個樣品之檢驗值＞100 MPN/g(mL)" },
  { month:3, date:"2026-03-03", country:"印尼", item:"木薯脆片", category:"甜味劑", violation:"甜味劑糖精0.03 g/kg、環己基(代)磺醯胺酸1 g/kg", standard:"非表列准用之食品範圍" },
  { month:3, date:"2026-03-03", country:"印尼", item:"木薯脆條", category:"防腐劑", violation:"苯甲酸1.6 g/kg", standard:"苯甲酸限量為1.0 g/kg以下" },
  { month:3, date:"2026-03-03", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"甜味劑糖精0.14 g/kg、環己基（代）磺醯胺酸0.08 g/kg", standard:"非表列准用之食品範圍" },
  { month:3, date:"2026-03-03", country:"越南", item:"糙米", category:"農藥殘留", violation:"克美素0.04 ppm", standard:"克美素於米類為不得檢出" },
  { month:3, date:"2026-03-03", country:"印尼", item:"木薯餅", category:"防腐劑", violation:"防腐劑己二烯酸0.3 g/kg", standard:"非表列准用之食品範圍" },
  { month:3, date:"2026-03-03", country:"印尼", item:"魚餅", category:"防腐劑", violation:"苯甲酸0.3 g/kg", standard:"苯甲酸於魚肉煉製品用量以Benzoic Acid計為1.0 g/kg以下" },
  { month:3, date:"2026-03-10", country:"美國", item:"糙米", category:"農藥殘留", violation:"協力精0.03 ppm", standard:"協力精於米類為不得檢出" },
  { month:3, date:"2026-03-10", country:"澳大利亞", item:"水晶蟹", category:"重金屬", violation:"甲基汞0.7 mg/kg", standard:"甲基汞於甲殼類之可食肌肉(包括附肢肌肉)限量為0.5 mg/kg" },
  { month:3, date:"2026-03-10", country:"印尼", item:"冷凍石斑魚片", category:"重金屬", violation:"甲基汞0.8 mg/kg", standard:"甲基汞於其他魚類限量為0.5 mg/kg" },
  { month:3, date:"2026-03-10", country:"韓國", item:"鮮柑橘", category:"農藥殘留", violation:"諾伐隆0.08 ppm", standard:"諾伐隆於柑橘為不得檢出" },
  { month:3, date:"2026-03-10", country:"中國大陸", item:"乾百合", category:"重金屬", violation:"鎘0.63 mg/kg", standard:"鎘於鱗莖類限量為0.05 mg/k" },
  { month:3, date:"2026-03-10", country:"印尼", item:"冷凍透抽", category:"重金屬", violation:"鎘2 mg/kg", standard:"鎘於頭足類(不含內臟)限量為1 mg/kg" },
  { month:3, date:"2026-03-10", country:"菲律賓", item:"紙碗", category:"衛生項目", violation:"檢出螢光增白劑", standard:"紙類螢光增白劑為不得檢出" },
  { month:3, date:"2026-03-10", country:"中國大陸", item:"紅棗", category:"農藥殘留", violation:"三氯松0.40 ppm、二氯松13.09 ppm", standard:"三氯松以其他*0.05 ppm為法規容許值；二氯松於紅棗為不得檢出，" },
  { month:3, date:"2026-03-10", country:"泰國", item:"蘆筍", category:"農藥殘留", violation:"氟尼胺0.03 ppm", standard:"氟尼胺以其他(蔬果類)*0.01 ppm為法規容許值" },
  { month:3, date:"2026-03-10", country:"印尼", item:"調製樹薯條", category:"甜味劑", violation:"糖精0.02 g/kg、環己基(代)磺醯胺酸 0.23 g/kg", standard:"非表列准用之食品範圍" },
  { month:3, date:"2026-03-10", country:"印度", item:"香芹子", category:"農藥殘留", violation:"得克利0.07 ppm", standard:"得克利以其他*0.05 ppm為法規容許值" },
  { month:3, date:"2026-03-10", country:"中國大陸", item:"紙杯", category:"溶出試驗", violation:"以4%醋酸(95℃,30分鐘)溶出試驗結果，蒸發殘渣值57 ppm", standard:"以紙類-與食品直接接觸面之部分為塑膠類，溶出試驗以4%醋酸(95℃,30分鐘)蒸發殘渣合格標準為30 ppm以下，。" },
  { month:3, date:"2026-03-10", country:"中國大陸", item:"紙杯", category:"溶出試驗", violation:"以4%醋酸(95℃,30分鐘)溶出試驗結果，蒸發殘渣值56 ppm", standard:"以紙類-與食品直接接觸面之部分為塑膠類，溶出試驗以4%醋酸(95℃,30分鐘)蒸發殘渣合格標準為30 ppm以下，。" },
  { month:3, date:"2026-03-10", country:"日本", item:"鮮草莓", category:"農藥殘留", violation:"賽芬蟎2.5 ppm", standard:"賽芬蟎於草莓容許量為2.0 ppm" },
  { month:3, date:"2026-03-17", country:"玻利維亞", item:"綠豆", category:"農藥殘留", violation:"芬普尼0.005 ppm", standard:"芬普尼以其他*0.001 ppm為法規容許值" },
  { month:3, date:"2026-03-17", country:"法國", item:"核桃油", category:"衛生項目", violation:"銅葉綠素A 0.1 ppm", standard:"產品非表列准用之食品範圍" },
  { month:3, date:"2026-03-17", country:"肯亞", item:"茵陳蒿", category:"農藥殘留", violation:"賽普洛0.10 ppm、滅達樂0.04 ppm、賜諾殺0.24 ppm、第滅寧0.06 ppm、待克利0.02 ppm", standard:"賽普洛、第滅寧、待克利皆以其他*0.01 ppm為法規容許值；滅達樂、賜諾殺於茵陳蒿皆為不得檢出" },
  { month:3, date:"2026-03-17", country:"日本", item:"抹茶粉", category:"農藥殘留", violation:"特安勃0.11 ppm", standard:"特安勃於茶類為不得檢出" },
  { month:3, date:"2026-03-17", country:"美國", item:"糙米", category:"農藥殘留", violation:"協力精0.03 ppm", standard:"協力精於米類為不得檢出" },
  { month:3, date:"2026-03-17", country:"印度", item:"馬芹籽", category:"農藥殘留", violation:"亞滅培0.30 ppm、亞托敏0.11 ppm、貝芬替0.20 ppm、可尼丁0.20 ppm、氟尼胺0.30 ppm、菲克利0.09 ppm、佈飛松0.39 ppm、賽速安0.10 ppm、脫芬瑞0.14 ppm、三賽唑0.05 ppm、芬普尼0.006 ppm、陶斯松0.44 ppm、賽滅寧0.08 ppm、得克利0.07 ppm", standard:"三賽唑為不得檢出，應低於檢測方法之定量極限0.05 ppm；陶斯松為不得檢出，應低於檢測方法之定量極限0.03 ppm；亞滅培、亞托敏、貝芬替、氟尼胺、菲克利、佈飛松、賽速安、脫芬瑞、得克利皆以其他*0.05 ppm為法規容許值；可尼丁、賽滅寧以其他*0.03 ppm為法規容許值；芬普尼以其他*0.002 ppm為法規容許值" },
  { month:3, date:"2026-03-17", country:"印度", item:"馬芹籽", category:"農藥殘留", violation:"農藥亞滅培0.33 ppm、亞托敏0.09 ppm、貝芬替0.29 ppm、可尼丁0.15 ppm、氟尼胺0.22 ppm、菲克利0.11 ppm、佈飛松0.30 ppm、賽速安0.09 ppm、脫芬瑞0.12 ppm、芬普尼0.005 ppm、陶斯松0.37 ppm、賽滅寧0.07 ppm、愛殺松0.09 ppm、得克利0.07 ppm", standard:"陶斯松為不得檢出；愛殺松為不得檢出；亞滅培、亞托敏、貝芬替、氟尼胺、菲克利、佈飛松、賽速安、脫芬瑞、得克利皆以其他*0.05 ppm為法規容許值；可尼丁、賽滅寧以其他*0.03 ppm為法規容許值；芬普尼以其他*0.002 ppm為法規容許值" },
  { month:3, date:"2026-03-17", country:"印度", item:"馬芹籽", category:"農藥殘留", violation:"農藥亞滅培0.36 ppm、亞托敏0.11 ppm、貝芬替0.26 ppm、可尼丁0.21 ppm、氟尼胺0.29 ppm、菲克利0.11 ppm、佈飛松0.42 ppm、賽速安0.11 ppm、脫芬瑞0.13 ppm、三賽唑0.05 ppm、芬普尼0.005 ppm、陶斯松0.47 ppm、賽滅寧0.09 ppm、愛殺松0.06 ppm、得克利0.07 ppm", standard:"陶斯松為不得檢出；愛殺松為不得檢出；亞滅培、亞托敏、貝芬替、氟尼胺、菲克利、佈飛松、賽速安、脫芬瑞、得克利皆以其他*0.05 ppm為法規容許值；可尼丁、賽滅寧以其他*0.03 ppm為法規容許值；芬普尼以其他*0.002 ppm為法規容許值" },
  { month:3, date:"2026-03-17", country:"印度", item:"胡荽籽", category:"農藥殘留", violation:"得克利0.10 ppm", standard:"得克利以其他*0.05 ppm為法規容許值" },
  { month:3, date:"2026-03-17", country:"印度", item:"胡荽籽", category:"農藥殘留", violation:"得克利0.16 ppm、賽洛寧0.04 ppm", standard:"得克利以其他*0.05 ppm為法規容許值；賽洛寧以其他*0.03 ppm為法規容許值" },
  { month:3, date:"2026-03-17", country:"印度", item:"胡荽籽", category:"農藥殘留", violation:"得克利0.14 ppm、賽洛寧0.04 ppm", standard:"得克利以其他*0.05 ppm為法規容許值；賽洛寧以其他*0.03 ppm為法規容許值" },
  { month:3, date:"2026-03-24", country:"泰國", item:"醃竹筍絲", category:"漂白劑", violation:"二氧化硫0.075 g/kg", standard:"准用亞硫酸鹽類漂白劑用量以二氧化硫殘留量計為0.030 g/kg以下" },
  { month:3, date:"2026-03-24", country:"印尼", item:"調味料(芫荽粉)", category:"農藥殘留", violation:"氟克殺0.07 ppm", standard:"氟克殺於香辛植物(種子)為不得檢出，應低於檢測方法之定量極限0.03 ppm" },
  { month:3, date:"2026-03-24", country:"日本", item:"安康魚肝", category:"重金屬", violation:"鎘0.17 mg/kg", standard:"鎘於其他魚類限量為0.05 mg/kg" },
  { month:3, date:"2026-03-24", country:"美國", item:"凱撒沙拉醬", category:"農藥殘留", violation:"環氧乙烷0.7 mg/kg", standard:"環氧乙烷為不得檢出" },
  { month:3, date:"2026-03-24", country:"中國大陸", item:"烏梅", category:"農藥殘留", violation:"2-phenylphenol 0.07 ppm", standard:"2-phenylphenol於梅為不得檢出" },
  { month:3, date:"2026-03-24", country:"土耳其", item:"月桂葉", category:"農藥殘留", violation:"亞滅培0.49 ppm、賽扶寧0.09 ppm、百利普芬0.11 ppm", standard:"亞滅培、百利普芬以其他* 0.05 ppm為法規容許值，賽扶寧以其他* 0.03 ppm為法規容許值" },
  { month:3, date:"2026-03-24", country:"阿根廷", item:"大蒜", category:"農藥殘留", violation:"大滅松0.43 ppm", standard:"大滅松於蒜頭為不得檢出" },
  { month:3, date:"2026-03-24", country:"韓國", item:"沾醬", category:"防腐劑", violation:"對羥苯甲酸乙酯(以對羥苯甲酸計) 0.085 g/kg，依", standard:"對羥苯甲酸乙酯於醬油用量以p-Hydroxybenzoic Acid計為0.25 g/kg以下" },
  { month:3, date:"2026-03-24", country:"中國大陸", item:"地瓜乾", category:"防腐劑/抗氧化劑", violation:"己二烯酸0.1 g/kg；二氧化硫0.17 g/kg", standard:"產品非表列准用之食品範圍" },
  { month:3, date:"2026-03-24", country:"越南", item:"黑胡椒", category:"農藥殘留", violation:"亞滅培0.06 ppm、益達胺0.06 ppm", standard:"亞滅培以其他*0.05 ppm為法規容許值；益達胺於胡椒容許量為0.05 ppm" },
  { month:3, date:"2026-03-31", country:"日本", item:"小卷", category:"重金屬", violation:"鎘 3 mg/kg", standard:"鎘於頭足類(不含內臟)限量為1 mg/k" },
  { month:3, date:"2026-03-31", country:"美國", item:"黃豆", category:"農藥殘留", violation:"美賜平0.18 ppm", standard:"美賜平於乾豆類為不得檢出" },
  { month:3, date:"2026-03-31", country:"美國", item:"Collagène飲品", category:"防腐劑", violation:"己二烯酸1.2 g/kg", standard:"不含碳酸飲料之防腐劑用量以Sorbic Acid 計為0.5 g/kg以下" },
  { month:3, date:"2026-03-31", country:"印尼", item:"白胡椒粉", category:"農藥殘留", violation:"賽速安0.13 ppm", standard:"賽速安於香辛植物(果實)為不得檢出" },
  { month:3, date:"2026-03-31", country:"馬來西亞", item:"咖喱粉", category:"農藥殘留", violation:"三賽唑0.08 ppm、芬普尼代謝物0.003 ppm(芬普尼及其代謝物之加總為0.003 ppm)，", standard:"芬普尼及其代謝物以其他*0.002 ppm為法規容許值；三賽唑於米類容許量為3.0 ppm，其他皆為不得檢出" },
  { month:3, date:"2026-03-31", country:"中國大陸", item:"蛋糕盒底托", category:"衛生項目", violation:"檢出螢光增白劑", standard:"紙類螢光增白劑不得檢出" },
  { month:3, date:"2026-03-31", country:"日本", item:"鮮哈密瓜", category:"農藥殘留", violation:"依普同0.04 ppm", standard:"依普同以其他*0.01 ppm為法規容許值" },
  { month:3, date:"2026-03-31", country:"法國", item:"乾酪", category:"微生物", violation:"大腸桿菌93 MPN/g、240 MPN/g、240 MPN/g、93 MPN/g、93 MPN/g", standard:"大腸桿菌於乾酪類之檢驗結果判定，5個樣品中，允許有≦2個樣品之微生物檢驗值介於10 MPN/g(mL)和100 MPN/g(mL)之間，但不得有任何一個樣品之檢驗值＞100 MPN/g(mL)，不符合食品安全衛生管理法第17條規定。" },
  { month:2, date:"2026-02-03", country:"越南", item:"草莓凍乾", category:"農藥殘留", violation:"脫芬瑞0.07 ppm", standard:"脫芬瑞以其他* 0.05 ppm為法規容許值" },
  { month:2, date:"2026-02-03", country:"義大利", item:"芝麻菜", category:"農藥殘留", violation:"護汰寧0.04 ppm", standard:"護汰寧以其他(蔬果類)*0.01 ppm為法規容許值" },
  { month:2, date:"2026-02-03", country:"中國大陸", item:"蓮藕片", category:"漂白劑", violation:"二氧化硫0.042 g/kg", standard:"准用亞硫酸鹽類漂白劑用量以二氧化硫殘留量計為0.030 g/kg以下" },
  { month:2, date:"2026-02-03", country:"印尼", item:"胡椒粒", category:"農藥殘留", violation:"芬普尼0.004 ppm", standard:"芬普尼及其代謝物以其他* 0.002 ppm為法規容許值" },
  { month:2, date:"2026-02-03", country:"韓國", item:"新鮮人參", category:"農藥殘留", violation:"賽普洛0.04 ppm、賽滅氟0.13 ppm、平硫瑞0.02 ppm", standard:"賽普洛以其他(蔬果類)*0.01 ppm為法規容許值，賽滅氟、平硫瑞於人參為不得檢出" },
  { month:2, date:"2026-02-03", country:"中國大陸", item:"紙袋", category:"溶出試驗", violation:"案內產品以4%醋酸(60℃，30分鐘)溶出試驗結果，蒸發殘渣值為40 ppm", standard:"以紙類與食品直接接觸面之部分為塑膠類，溶出試驗以4%醋酸(60℃,30分鐘)蒸發殘渣值合格標準為30 ppm以下" },
  { month:2, date:"2026-02-03", country:"中國大陸", item:"速凍馬蹄丁", category:"農藥殘留", violation:"克美素0.03 ppm", standard:"克美素於根莖菜類為不得檢出" },
  { month:2, date:"2026-02-03", country:"德國", item:"膠原蛋白水果安瓶飲", category:"防腐劑", violation:"己二烯酸1.4 g/kg", standard:"不含碳酸飲料類之防腐劑用量以Sorbic Acid 計為0.5 g/kg以下" },
  { month:2, date:"2026-02-03", country:"泰國", item:"蘆筍", category:"農藥殘留", violation:"達有龍0.26 ppm", standard:"達有龍於蘆筍容許量為0.05 ppm" },
  { month:2, date:"2026-02-03", country:"中國大陸", item:"餐盒", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"以紙類與食品直接接觸面之部分為蠟或紙漿製品者為不得檢出" },
  { month:2, date:"2026-02-03", country:"越南", item:"黑糯糙米", category:"農藥殘留", violation:"克美素0.02 ppm", standard:"克美素於米為不得檢出" },
  { month:2, date:"2026-02-03", country:"中國大陸", item:"乾苦瓜片", category:"農藥殘留", violation:"祿芬隆0.08 ppm", standard:"祿芬隆以其他* 0.05 ppm為法規容許值" },
  { month:2, date:"2026-02-03", country:"越南", item:"黑胡椒粒", category:"著色劑", violation:"蘇丹色素四號", standard:"屬不得使用之物質" },
  { month:2, date:"2026-02-03", country:"日本", item:"鮮草莓", category:"農藥殘留", violation:"芬普蟎0.8 ppm", standard:"芬普蟎於小漿果類容許量為0.5 ppm" },
  { month:2, date:"2026-02-10", country:"印度", item:"茴香子", category:"農藥殘留", violation:"待克利0.06 ppm", standard:"待克利以其他*0.05 ppm為法規容許值" },
  { month:2, date:"2026-02-10", country:"印度", item:"胡荽子", category:"農藥殘留", violation:"芬普尼0.011 ppm", standard:"待克利以其他*0.05 ppm為法規容許值" },
  { month:2, date:"2026-02-10", country:"越南", item:"白米", category:"農藥殘留", violation:"陶斯松0.06 ppm", standard:"陶斯松於米類為不得檢出" },
  { month:2, date:"2026-02-10", country:"日本", item:"紫蘇葉", category:"農藥殘留", violation:"必芬蟎0.07 ppm、賽芬蟎0.02 ppm、平硫瑞1.97 ppm", standard:"賽芬蟎以其他*0.01 ppm為法規容許值；必芬蟎、平硫瑞於紫蘇葉皆為不得檢出" },
  { month:2, date:"2026-02-10", country:"越南", item:"冷凍地瓜", category:"農藥殘留", violation:"克美素0.02 ppm", standard:"克美素於根莖菜類為不得檢出" },
  { month:2, date:"2026-02-10", country:"緬甸", item:"黑芝麻", category:"農藥殘留", violation:"巴賽松0.03 ppm", standard:"巴賽松於乾豆類為不得檢出" },
  { month:2, date:"2026-02-10", country:"緬甸", item:"薑黃粉", category:"農藥殘留", violation:"磷化氫0.78 ppm", standard:"磷化氫於香辛植物類容許量為0.01 ppm" },
  { month:2, date:"2026-02-10", country:"中國大陸", item:"蜜薯", category:"漂白劑", violation:"二氧化硫0.064 g/k", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-10", country:"中國大陸", item:"蜜薯", category:"漂白劑", violation:"二氧化硫0.052 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-10", country:"中國大陸", item:"蒟蒻粉", category:"漂白劑", violation:"二氧化硫1.17 g/kg", standard:"非直接供食用之蒟蒻原料，用量以SO2殘留量計為0.90 g/kg以下" },
  { month:2, date:"2026-02-10", country:"日本", item:"哈密瓜", category:"農藥殘留", violation:"依普同0.57 ppm", standard:"依普同依普同以其他(蔬果類)* 0.01 ppm為法規容許值" },
  { month:2, date:"2026-02-10", country:"印尼", item:"調製豆", category:"真菌毒素", violation:"黃麴毒素B1 158 µg/kg、總黃麴毒素233 µg/kg", standard:"供直接食用之花生、油籽、黃豆，及其加工產品，去殼黃麴毒素B1限量為2 µg/kg、總黃麴毒素限量為4 µg/kg" },
  { month:2, date:"2026-02-10", country:"中國大陸", item:"冷凍薺菜丁", category:"農藥殘留", violation:"派美尼 0.03 ppm", standard:"派美尼於薺菜為不得檢出" },
  { month:2, date:"2026-02-10", country:"日本", item:"鮮溫州蜜柑", category:"農藥殘留", violation:"Cyclaniliprole 0.02 ppm", standard:"Cyclaniliprole於蜜柑為不得檢出" },
  { month:2, date:"2026-02-10", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"糖精0.06 g/kg、環己基（代）磺醯胺酸0.91 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-10", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"糖精0.05 g/kg、環己基（代）磺醯胺酸 1.11 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-10", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"環己基（代）磺醯胺酸0.03 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-10", country:"印尼", item:"香蕉餅", category:"甜味劑", violation:"環己基（代）磺醯胺酸0.08 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-10", country:"印尼", item:"香蕉餅", category:"甜味劑", violation:"糖精0.13 g/kg、環己基（代）磺醯胺酸1.52 g/k", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-24", country:"中國大陸", item:"薄荷", category:"農藥殘留", violation:"貝芬替1.34 ppm、待克利0.70 ppm、得克利0.06 ppm、賽洛寧0.11 ppm、Chlorbenzuron 0.15 ppm", standard:"貝芬替、待克利及得克利皆以其他* 0.05 ppm為法規容許值、賽洛寧以其他* 0.03 ppm為法規容許值、Chlorbenzuron於薄荷為不得檢出" },
  { month:2, date:"2026-02-24", country:"菲律賓", item:"餅乾", category:"防腐劑", violation:"己二烯酸0.05 g/kg", standard:"防腐劑己二烯酸鉀於人造奶油，用量以Sorbic Acid計為1.0 g/kg以下" },
  { month:2, date:"2026-02-24", country:"法國", item:"新鮮波特菇", category:"農藥殘留", violation:"滅芬農0.02 ppm", standard:"滅芬農於波特菇為不得檢出" },
  { month:2, date:"2026-02-24", country:"越南", item:"冷凍巴沙魚片", category:"保水劑", violation:"磷酸鹽4 g/kg", standard:"磷酸鹽類用量以Phosphate計為3 g/kg以下" },
  { month:2, date:"2026-02-24", country:"中國大陸", item:"紙盤", category:"螢光增白劑", violation:"檢出螢光增白劑", standard:"螢光增白劑為不得檢出" },
  { month:2, date:"2026-02-24", country:"日本", item:"安康魚肝", category:"重金屬", violation:"鎘0.07 mg/kg", standard:"鎘於其他魚類限量為0.05 mg/kg" },
  { month:2, date:"2026-02-24", country:"日本", item:"烏賊", category:"重金屬", violation:"鎘6 mg/kg", standard:"鎘於頭足類(不含內臟)限量為1 mg/kg" },
  { month:2, date:"2026-02-24", country:"中國大陸", item:"冷凍調製扇貝", category:"保水劑", violation:"磷酸鹽6 g/kg", standard:"磷酸鹽限量為3 g/kg以下" },
  { month:2, date:"2026-02-24", country:"越南", item:"冷凍金桔汁", category:"農藥殘留", violation:"菲克利0.03 ppm", standard:"菲克利以其他(蔬果類)*0.01 ppm為法規容許值" },
  { month:2, date:"2026-02-24", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"糖精0.02 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:2, date:"2026-02-24", country:"日本", item:"哈密瓜", category:"農藥殘留", violation:"畢達本0.03 ppm、脫芬瑞0.02 ppm", standard:"畢達本於哈密瓜為不得檢出，應低於檢測方法之定量極限0.01 ppm；脫芬瑞以其他(蔬果類)*0.01 ppm為法規容許值" },
  { month:2, date:"2026-02-24", country:"中國大陸", item:"乾桂花", category:"農藥殘留", violation:"畢芬寧0.06 ppm、陶斯松0.04 ppm", standard:"畢芬寧以其他*0.03 ppm 為法規容許值；陶斯松為不得檢出" },
  { month:1, date:"2026-01-06", country:"中國大陸", item:"花椒", category:"農藥殘留", violation:"益達胺0.08 ppm", standard:"益達胺以其他* 0.05 ppm為法規容許值" },
  { month:1, date:"2026-01-06", country:"中國大陸", item:"鮮藍莓", category:"農藥殘留", violation:"滅脫定0.05 ppm", standard:"滅脫定於藍莓為不得檢出" },
  { month:1, date:"2026-01-06", country:"美國", item:"冷凍雞腿", category:"動物用藥", violation:"硝基砆喃代謝物Semicarbazide (SC) 1.1 ppb", standard:"硝基呋喃代謝物於食品中為不得檢出" },
  { month:1, date:"2026-01-06", country:"日本", item:"山椒粉", category:"農藥殘留", violation:"亞滅培0.54 ppm、克凡派4.18 ppm、克收欣12.91 ppm、滅大松0.13 ppm", standard:"亞滅培、克凡派、克收欣皆以其他* 0.05 ppm為法規容許值，滅大松為不得檢出" },
  { month:1, date:"2026-01-06", country:"日本", item:"鮮甘藷", category:"農藥殘留", violation:"農藥芬普尼0.002 ppm、芬普尼代謝物0.003 ppm，芬普尼及其代謝物之加總為0.005 ppm", standard:"芬普尼及其代謝物於甘藷容許量為0.002 ppm" },
  { month:1, date:"2026-01-06", country:"澳大利亞", item:"薄荷茶", category:"農藥殘留", violation:"陶斯松0.07 ppm", standard:"陶斯松於草木本植物為不得檢出" },
  { month:1, date:"2026-01-06", country:"西班牙", item:"軟糖", category:"著色劑", violation:"著色劑偶氮玉紅", standard:"偶氮玉紅非屬表列准用之食品添加物" },
  { month:1, date:"2026-01-06", country:"中國大陸", item:"蛋糕用刀叉組", category:"溶出試驗", violation:"案內產品以4％醋酸（60℃,30分鐘）溶出試驗結果，其中2件蒸發殘渣值分別為36 ppm(刀)、37 ppm(叉)", standard:"以聚苯乙烯為合成原料之塑膠類，其溶出試驗4％醋酸（60℃,30分鐘）蒸發殘渣合格標準為30 ppm以下" },
  { month:1, date:"2026-01-06", country:"泰國", item:"炒粿條", category:"甜味劑", violation:"糖精0.13 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:1, date:"2026-01-06", country:"泰國", item:"冷凍旭蟹", category:"重金屬", violation:"鎘2.1 mg/kg", standard:"鎘於甲殼類之可食肌肉（包括附肢肌肉）限量為0.5 mg/kg" },
  { month:1, date:"2026-01-06", country:"中國大陸", item:"冷凍黃秋葵", category:"農藥殘留", violation:"勃激素A3 0.01 ppm", standard:"勃激素A3於秋葵為不得檢出" },
  { month:1, date:"2026-01-06", country:"中國大陸", item:"菜脯米", category:"農藥殘留", violation:"福賽絕0.05 ppm", standard:"福賽絕於根莖菜類為不得檢出" },
  { month:1, date:"2026-01-06", country:"埃及", item:"羅勒葉", category:"農藥殘留", violation:"依芬寧0.21 ppm", standard:"依芬寧於小葉菜類為不得檢出" },
  { month:1, date:"2026-01-06", country:"法國", item:"乾酪", category:"微生物", violation:"大腸桿菌75 MPN/g、460 MPN/g、43 MPN/g、43 MPN/g、240 MPN/g", standard:"大腸桿菌於乾酪類之檢驗結果判定，5個樣品中，允許有≦2個樣品之微生物檢驗值介於10 MPN/g(mL)和100 MPN/g(mL)之間，但不得有任何一個樣品之檢驗值＞100 MPN/g(mL)" },
  { month:1, date:"2026-01-06", country:"日本", item:"鮮草莓", category:"農藥殘留", violation:"賽芬蟎5.0 ppm", standard:"賽芬蟎於草莓容許量為2.0 ppm" },
  { month:1, date:"2026-01-13", country:"中國大陸", item:"空膠囊", category:"農藥殘留", violation:"環氧乙烷0.5 mg/kg", standard:"環氧乙烷為不得檢出" },
  { month:1, date:"2026-01-13", country:"印尼", item:"香蕉點心", category:"甜味劑", violation:"檢出甜味劑糖精、環己基 (代) 磺醯胺酸", standard:"案內產品非表列准用之食品範圍" },
  { month:1, date:"2026-01-13", country:"中國大陸", item:"靈芝", category:"農藥殘留", violation:"陶斯松0.05 ppm", standard:"陶斯松於蕈菜類為不得檢出" },
  { month:1, date:"2026-01-13", country:"中國大陸", item:"紙盒", category:"溶出試驗", violation:"案內產品以4%醋酸(60℃，30分鐘)溶出試驗結果，蒸發殘渣值為 1,556 ppm", standard:"以紙類與食品直接接觸面之部分為塑膠類，其溶出試驗4%醋酸(60℃，30分鐘)蒸發殘渣值合格標準為30 ppm以下" },
  { month:1, date:"2026-01-13", country:"菲律賓", item:"鮪魚罐", category:"防腐劑", violation:"苯甲酸0.07 g/kg", standard:"依業者提供成分比例換算苯甲酸於醬油之用量為1.1 g/kg，依據「食品添加物使用範圍及限量暨規格標準」，醬油防腐劑用量以Benzoic Acid計為1.0 g/kg以下" },
  { month:1, date:"2026-01-13", country:"印度", item:"薑黃粉", category:"農藥殘留", violation:"磷化氫0.02 ppm", standard:"磷化氫於香辛植物類容許量為0.01 ppm" },
  { month:1, date:"2026-01-13", country:"中國大陸", item:"冷凍蘿蔔葉", category:"農藥殘留", violation:"陶斯松0.02 ppm", standard:"陶斯松於蘿蔔葉為不得檢出" },
  { month:1, date:"2026-01-13", country:"印尼", item:"木薯餅", category:"甜味劑", violation:"糖精0.12 g/kg", standard:"案內產品非表列准用之食品範圍" },
  { month:1, date:"2026-01-13", country:"日本", item:"鮮草莓", category:"農藥殘留", violation:"亞派占0.28 ppm", standard:"亞派占於草莓為不得檢出" },
  { month:1, date:"2026-01-13", country:"日本", item:"鮮草莓", category:"農藥殘留", violation:"賽芬蟎2.5 ppm", standard:"賽芬蟎於草莓容許量為2.0 ppm" },
  { month:1, date:"2026-01-20", country:"印尼", item:"冷凍小鯊魚", category:"重金屬", violation:"鎘0.07 mg/kg", standard:"鎘於其他魚類限量為0.05 mg/kg" },
  { month:1, date:"2026-01-20", country:"馬來西亞", item:"黑胡椒粒", category:"農藥殘留", violation:"賽速安0.08 ppm", standard:"賽速安以其他* 0.05 ppm為法規容許值" },
  { month:1, date:"2026-01-20", country:"智利", item:"油桃", category:"農藥殘留", violation:"Fenhexamid 0.04 ppm", standard:"Fenhexamid於油桃為不得檢出" },
  { month:1, date:"2026-01-20", country:"中國大陸", item:"辣椒段", category:"著色劑", violation:"蘇丹色素三號", standard:"屬不得使用之物質" },
  { month:1, date:"2026-01-20", country:"中國大陸", item:"鮮奇異果", category:"農藥殘留", violation:"白克列0.02 ppm、百克敏0.08 ppm、三氟敏0.03 ppm、氟派瑞0.05 ppm、氟克殺0.01 ppm、滅芬座0.04 ppm及Triflumuron 0.02 ppm", standard:"白克列、百克敏及三氟敏皆以其他(蔬果類)*0.01 ppm為法規容許值，氟派瑞、氟克殺、滅芬座及Triflumuron皆於奇異果為不得檢出" },
  { month:1, date:"2026-01-20", country:"義大利", item:"鮮奇異果", category:"農藥殘留", violation:"依芬寧0.02 ppm", standard:"依芬寧於大漿果類為不得檢出" },
  { month:1, date:"2026-01-20", country:"日本", item:"冷凍桃", category:"農藥殘留", violation:"索林酸0.10 ppm", standard:"歐索林酸於梨果類為不得檢出" },
  { month:1, date:"2026-01-20", country:"馬來西亞", item:"辣椒粉", category:"農藥殘留", violation:"芬普尼0.004 ppm", standard:"芬普尼及其代謝物以其他* 0.002 ppm為法規容許值" },
  { month:1, date:"2026-01-20", country:"越南", item:"冷凍鱔魚片", category:"動物用藥", violation:"結晶紫1.2 ppb", standard:"結晶紫於魚為不得檢出" },
  { month:1, date:"2026-01-20", country:"法國", item:"乾燥羊肚菌", category:"農藥殘留", violation:"磷化氫0.12 ppm", standard:"磷化氫於蔬菜(乾)容許量為0.01 ppm" },
  { month:1, date:"2026-01-20", country:"日本", item:"鮮哈密瓜", category:"農藥殘留", violation:"Nitenpyram 0.09 ppm", standard:"Nitenpyram於哈密瓜為不得檢出" },
  { month:1, date:"2026-01-20", country:"菲律賓", item:"香蕉醬", category:"著色劑", violation:"莧菜紅", standard:"莧菜紅非表列准用之食品添加物" },
  { month:1, date:"2026-01-20", country:"越南", item:"糙米", category:"農藥殘留", violation:"克美素0.03 ppm", standard:"克美素於米為不得檢出" },
  { month:1, date:"2026-01-20", country:"日本", item:"蜜柑", category:"農藥殘留", violation:"賽安勃0.02 ppm", standard:"賽安勃於蜜柑為不得檢出" },
  { month:1, date:"2026-01-20", country:"日本", item:"醬油", category:"防腐劑", violation:"雙十二烷基硫酸硫胺明0.02 g/kg", standard:"雙十二烷基硫酸硫胺明用量以Laurylsulfate計為 0.01 g/kg以下" },
  { month:1, date:"2026-01-20", country:"日本", item:"鮮草莓", category:"農藥殘留", violation:"亞派占0.19 ppm", standard:"亞派占於草莓為不得檢出" },
  { month:1, date:"2026-01-27", country:"美國", item:"鮮石榴", category:"農藥殘留", violation:"護汰寧3.9 ppm", standard:"護汰寧於石榴容許量為2.0 ppm" },
  { month:1, date:"2026-01-27", country:"馬來西亞", item:"猴頭菇", category:"漂白劑", violation:"二氧化硫0.066 g/kg", standard:"其他加工食品用量以SO2殘留量計為0.030 g/kg以下" },
  { month:1, date:"2026-01-27", country:"日本", item:"煙燻起司魷魚", category:"保水劑", violation:"磷酸鹽 9 g/kg", standard:"磷酸鹽類用量以Phosphate計為3 g/kg以下" },
  { month:1, date:"2026-01-27", country:"西班牙", item:"米", category:"農藥殘留", violation:"第滅寧0.28 ppm、協力精4.33 ppm", standard:"第滅寧於米類容許量為0.05 ppm、協力精為不得檢出" },
  { month:1, date:"2026-01-27", country:"馬來西亞", item:"薑黃粉", category:"農藥殘留", violation:"第滅寧0.28 ppm、協力精4.33 ppm", standard:"陶斯松於香辛植物及其他草木本植物類為不得檢出" },
  { month:1, date:"2026-01-27", country:"智利", item:"油桃", category:"農藥殘留", violation:"Fenhexamid 0.06 ppm", standard:"Fenhexamid於油桃為不得檢出" },
  { month:1, date:"2026-01-27", country:"日本", item:"柚子絲", category:"農藥殘留", violation:"賽達松0.03 ppm", standard:"賽達松以其他*0.01 ppm為法規容許值" },
  { month:1, date:"2026-01-27", country:"印尼", item:"蝦醬塊", category:"防腐劑", violation:"對羥苯甲酸0.14 g/kg", standard:"對羥苯甲酸非表列准用之食品添加物" },
  { month:1, date:"2026-01-27", country:"法國", item:"乾燥羊肚菌", category:"農藥殘留", violation:"可尼丁0.94 ppm", standard:"可尼丁於蕈菜類容許量為0.05 ppm" },
  { month:1, date:"2026-01-27", country:"中國大陸", item:"紙盒", category:"溶出試驗", violation:"案內產品以4%醋酸(60℃，30分鐘)溶出試驗結果，蒸發殘渣值為1,296 ppm", standard:"以紙類與食品直接接觸面之部分為塑膠類，其溶出試驗4%醋酸(60℃，30分鐘)蒸發殘渣值合格標準為30 ppm以下" },
  { month:1, date:"2026-01-27", country:"中國大陸", item:"空膠囊", category:"農藥殘留", violation:"環氧乙烷6.1 mg/kg", standard:"環氧乙烷為不得檢出" },
  { month:1, date:"2026-01-27", country:"中國大陸", item:"空膠囊", category:"農藥殘留", violation:"環氧乙烷9.2 mg/kg", standard:"脫芬瑞以其他* 0+E54.05 ppm為法規容許值" },
  { month:1, date:"2026-01-27", country:"中國大陸", item:"空膠囊", category:"農藥殘留", violation:"環氧乙烷7.0 mg/kg", standard:"環氧乙烷為不得檢出" },
  { month:1, date:"2026-01-27", country:"中國大陸", item:"空膠囊", category:"農藥殘留", violation:"環氧乙烷18.9 mg/kg", standard:"環氧乙烷為不得檢出" },
  { month:1, date:"2026-01-27", country:"中國大陸", item:"紅甜椒片", category:"農藥殘留", violation:"可尼丁0.1 ppm", standard:"可尼丁於其他果菜類(番茄除外)容許量為0.05 ppm" },
  { month:1, date:"2026-01-27", country:"印尼", item:"脆皮花生", category:"真菌毒素", violation:"總黃麴毒素24 µg/kg、黃麴毒素B1 21 µg/kg", standard:"供直接食用之花生、油籽、黃豆，及其加工產品，去殼，總黃麴毒素限量為4 µg/kg、黃麴毒素B1限量為2 µg/kg" },
  { month:1, date:"2026-01-27", country:"印尼", item:"調製豆", category:"真菌毒素", violation:"總黃麴毒素367 µg/kg、黃麴毒素B1 364 µg/kg", standard:"供直接食用之花生、油籽、黃豆，及其加工產品，去殼，總黃麴毒素限量為4 µg/kg、黃麴毒素B1限量為2 µg/kg" },
  { month:1, date:"2026-01-27", country:"越南", item:"鮮榴槤", category:"農藥殘留", violation:"滅達樂0.03 ppm", standard:"滅達樂於榴槤為不得檢出" },
];
